"""Train the Echo readiness classifier and export it as portable C.

Input:  a CSV of RR-interval windows, or the synthetic generator below.
Output: core/echo_model.h  (scaler constants + flattened forest)
        bench/testvectors.h (parity fixtures shared with the C core)

PLACEHOLDER DATA WARNING
------------------------
`synthesize()` produces physiologically shaped but *fabricated* data so the
pipeline runs end to end on day one. It is not evidence of anything. Replace
it with WESAD/SWELL-derived windows, or real Polar H10 captures, before any
accuracy number leaves this repo.
"""
import argparse
import hashlib
import json
import pathlib
import sys

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from features import FEATURE_NAMES, N_FEATURES, extract  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATES = ["GREEN", "AMBER", "RED"]


def synthesize(n_per_class=1200, seed=7):
    """Fabricated RR windows with class-dependent HR and HRV structure."""
    rng = np.random.default_rng(seed)
    profiles = [
        # (mean HR, HRV scale, drift ms/beat)
        (62.0, 55.0, 0.0),    # GREEN: low HR, high variability, stable
        (88.0, 28.0, -0.35),  # AMBER: elevated, variability compressing
        (118.0, 11.0, -0.9),  # RED:   high HR, variability collapsed
    ]
    X, y = [], []
    for label, (hr, hrv, drift) in enumerate(profiles):
        for _ in range(n_per_class):
            beats = int(rng.integers(45, 110))
            base = 60000.0 / (hr + rng.normal(0, 6))
            noise = rng.normal(0, max(hrv + rng.normal(0, 6), 3.0), beats)
            trend = drift * np.arange(beats) * rng.uniform(0.5, 1.5)
            rr = base + noise + trend
            f = extract(rr)
            if f is not None:
                X.append(f)
                y.append(label)
    return np.array(X), np.array(y)


def flatten(forest):
    """sklearn forest -> flat parallel arrays for the C traversal loop."""
    feature, threshold, left, right, leaf, roots = [], [], [], [], [], []
    for est in forest.estimators_:
        t = est.tree_
        roots.append(len(feature))
        base = len(feature)
        for i in range(t.node_count):
            is_leaf = t.children_left[i] == -1
            feature.append(-1 if is_leaf else int(t.feature[i]))
            threshold.append(0.0 if is_leaf else float(t.threshold[i]))
            left.append(-1 if is_leaf else base + int(t.children_left[i]))
            right.append(-1 if is_leaf else base + int(t.children_right[i]))
            leaf.append(int(np.argmax(t.value[i][0])) if is_leaf else 0)
    return feature, threshold, left, right, leaf, roots


def carray(name, ctype, values, fmt=str, per_line=12):
    rows = []
    for i in range(0, len(values), per_line):
        rows.append("    " + " ".join(fmt(v) + "," for v in values[i:i + per_line]))
    body = "\n".join(rows)
    return f"static const {ctype} {name}[{len(values)}] = {{\n{body}\n}};\n"


def export_header(path, scaler, forest, model_id):
    feature, threshold, left, right, leaf, roots = flatten(forest)
    def f(v):
        s = f"{v:.9g}"
        if not any(c in s for c in ".eE"):
            s += ".0"
        return s + "f"

    inv_scale = [1.0 / s if s else 0.0 for s in scaler.scale_]

    out = [
        "/* GENERATED by train/train.py — do not edit by hand. */",
        "#ifndef ECHO_MODEL_H",
        "#define ECHO_MODEL_H",
        "#include <stdint.h>",
        "",
        f'#define ECHO_MODEL_ID "{model_id}"',
        f"#define ECHO_N_TREES {len(roots)}",
        f"#define ECHO_N_NODES {len(feature)}",
        "",
        carray("ECHO_SCALER_MEAN", "float", list(scaler.mean_), f),
        carray("ECHO_SCALER_INV_SCALE", "float", inv_scale, f),
        carray("ECHO_TREE_ROOT", "int32_t", roots),
        carray("ECHO_FEATURE", "int8_t", feature),
        carray("ECHO_THRESHOLD", "float", threshold, f),
        carray("ECHO_LEFT", "int32_t", left),
        carray("ECHO_RIGHT", "int32_t", right),
        carray("ECHO_LEAF_CLASS", "uint8_t", leaf),
        "#endif /* ECHO_MODEL_H */",
    ]
    path.write_text("\n".join(out))


def _cf(v):
    s = f"{v:.9g}"
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s + "f"


def export_testvectors(path, X, y_pred, n=64):
    rows = []
    for i in range(min(n, len(X))):
        vals = ", ".join(_cf(v) for v in X[i])
        rows.append(f"    {{ {{ {vals} }}, {int(y_pred[i])} }},")
    body = "\n".join(rows)
    path.write_text(
        "/* GENERATED by train/train.py — parity fixtures. */\n"
        "#ifndef ECHO_TESTVECTORS_H\n#define ECHO_TESTVECTORS_H\n\n"
        "typedef struct { float f[8]; int expect; } echo_fixture_t;\n\n"
        f"static const echo_fixture_t ECHO_FIXTURES[{min(n, len(X))}] = {{\n{body}\n}};\n\n"
        "#endif\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trees", type=int, default=100)
    ap.add_argument("--depth", type=int, default=15)
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    X, y = synthesize(seed=args.seed)
    print(f"windows: {len(X)}  features: {N_FEATURES} ({', '.join(FEATURE_NAMES)})")

    Xtr, Xte, ytr, yte = train_test_split(
        X, y, test_size=0.25, random_state=args.seed, stratify=y
    )

    scaler = StandardScaler().fit(Xtr)
    forest = RandomForestClassifier(
        n_estimators=args.trees,
        max_depth=args.depth,
        class_weight="balanced",
        random_state=args.seed,
        n_jobs=-1,
    ).fit(scaler.transform(Xtr), ytr)

    pred = forest.predict(scaler.transform(Xte))
    print(classification_report(yte, pred, target_names=STATES, digits=3))
    print("NOTE: trained on synthetic data. Accuracy above is not evidence.")

    model_id = hashlib.sha256(
        json.dumps({"trees": args.trees, "depth": args.depth,
                    "seed": args.seed, "feats": FEATURE_NAMES}).encode()
    ).hexdigest()[:12]

    export_header(ROOT / "core" / "echo_model.h", scaler, forest, model_id)
    export_testvectors(ROOT / "bench" / "testvectors.h", Xte, pred)
    print(f"wrote core/echo_model.h  (model {model_id}, "
          f"{args.trees} trees)")
    print("wrote bench/testvectors.h")


if __name__ == "__main__":
    main()
